config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :path_names => {:sign_up => "register"}

  # root 'application#index'
  # resources :users do #???????? вложения?
  #   resources :hotels
  # end
  resources :hotels do
    resources :comments
  end

  namespace :api do
  	namespace :v1 do
  		resources :hotels, except: [:new, :edit]
  	end
  end

  root 'application#index'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user
  before_save {commenter.downcase!}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :commenter, presence:true, format: {with: VALID_EMAIL_REGEX}
  validates :body, presence:true, length: {minimum: 5, maximum: 255}
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  mount_uploader :photo, HotelUploader
  validates :title, presence: true
  has_many :comments, dependent: :destroy
  paginates_per 6
  ratyrate_rateable "rating"
  belongs_to :user

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hotels
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  # attr_accessor :email, :password, :password_confirmation
end

app/controllers/api/v1/hotels_controller.rb
class Api::V1::HotelsController < ApplicationController

	before_action :require_fields, only: [:create, :update]
	respond_to :json

	def index
		hotels = Hotel.all
		render json: hotels, status: 200
	end

	def create
		if user_signed_in?
			hotel=Hotel.new (require_fields)

			if hotel.save
				render json: {success: true}, status: 200
			else
				render json: {success: false}, status: 400
			end
		else
			render json: {success: false}, status: 401
		end
	end

	def show
		hotel = Hotel.find(params[:id])
		render json: hotel, status: 200
	end

	def update
		if user_signed_in?
			hotel = Hotel.find(params[:id])
			if hotel.update(require_fields)
				render json: {success: true}, status: 200
			else
				render json: {success: false}, status: 400
			end
		else
			render json: {success: false}, status: 401
		end
	end

	def destroy
		if user_signed_in?
			hotel = Hotel.find(params[:id])
			if hotel.destroy
				render json: {success: true}, status: 200
			else
				render json: {success: false}, status: 400
			end
		else
			render json: {success: false}, status: 401
		end
	end

	private

	def require_fields
		params.require(:hotel).permit(:title, :breakfast, :description, :price, :photo, :country, :state, :city, :street)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # add_breadcrumb "Home", :root_path

	def index
		# load top5 hotels
    @hotels = Hotel.joins('INNER JOIN rating_caches ON rating_caches.cacheable_id=hotels.id').order('rating_caches.avg DESC').limit(5)
	end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in) do |user_params|
        user_params.permit(:username, :email)
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment_params, only: [:create]
  # before_filter :authenticate_user!

  def create
    @hotel = Hotel.find(params[:hotel_id])
    @comment = @hotel.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to @hotel
  end

  def destroy
    @hotel = Hotel.find(params[:hotel_id])
    @comment = @hotel.comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
    end
    redirect_to @hotel
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	before_action :require_fields, only: [:create, :update]
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	add_breadcrumb "Home", :root_path # добвлено в 10:42 6.07   Убирает крошку Home на главной странице
	add_breadcrumb "Hotels", :hotels_path

	def index
		@hotels = Hotel.page(params[:page])
	end

	def create
		@hotel=Hotel.new (require_fields)
		@hotel.user = current_user

		if @hotel.save
			redirect_to @hotel
		else
			render 'new'
		end
	end

	# def create
	# 	@user = User.find(params[:user_id])
	# 	@hotel = @user.hotels.create(require_fields)
	# 	redirect_to user_path(@hotel)
	# end

	def new
		add_breadcrumb "New hotel"
		@hotel=Hotel.new # for break form validation
	end

	def edit
		add_breadcrumb "Edit hotel"
		@hotel = Hotel.find(params[:id])
	end

	def show
		add_breadcrumb "Details hotel"
		@hotel = Hotel.find(params[:id])
	end

	def update
		# handle edit hotel
		@hotel = Hotel.find(params[:id])
		if @hotel.update(require_fields)
			redirect_to hotels_path
		else
			render 'edit'
		end
	end

	def destroy
		# handle delete hotel
		@hotel = Hotel.find(params[:id])
		if @hotel.destroy
			redirect_to hotels_path
		else
			redirect_to @hotel
		end
	end

	private

		def require_fields
			params.require(:hotel).permit(:title, :breakfast, :description, :price, :photo, :country, :state, :city, :street)
		end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def help
  	# add_breadcrumb "home", :help_path
  end

  def about
  	# add_breadcrumb "home", :about_path
  end

  def contact
  	# add_breadcrumb "home", :contact_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # add_breadcrumb "Home", :root_path

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Hotel Advisor"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.haml
.center.hero-unit
  %h1
    %center Welcome to the hotel advisor!
  %br
  - @hotels.each do |hotel|
    %div.hotel
      - if hotel.photo.file.nil?
        %img{:alt => "hotel photo", :src => "/img/no-hotel.png", :width => "200"}
      - else
        %img{:alt => "hotel photo", :src => hotel.photo.thumb, :width => "200"}
      %div.data
        - if hotel.title.length > 12
          %h2
            %marquee
              =hotel.title
        -else
          %h2
            =hotel.title
        %p=rating_for hotel, 'rating', disable_after_rate: true
        %p
          Breakfast included: #{ hotel.breakfast==1 ? " Yes" :" No" }
        - if !hotel.price.nil?
          %p
            Price for room:#{hotel.price} $
        - else
          %p &nbsp;
        = link_to hotel_path(hotel), {class: 'button'} do
          %span
            Read More

= link_to hotels_path, {class:'button'} do
  %span
    All hotels

app/views/comments/_comment.html.haml
%br
%strong
  = comment.commenter
  %strong :
= comment.body
/- if current_user.email.eql?("admin@email.admin")
%br


- if user_signed_in? && comment.user == current_user
  %p=link_to 'Delete comment', [comment.hotel, comment], method: :delete, data: {confirm: 'Are you sure?'}, class: 'button'
  %p
    =link_to [comment.hotel, comment], method: :delete, data: {confirm: 'Are you sure?'}, class: 'button' do
      %span
        Delete
%hr

app/views/comments/_comment_form.html.haml
= simple_form_for([@hotel, @hotel.comments.build]) do |f|
  %p
    = f.label :email
    %br
    = f.input :commenter, label: false, input_html: {value: "#{current_user.email}" }, placeholder: 'user@domain.com'
  %p
    = f.label :comment
    %br
    = f.text_area :body, required: true, placeholder: 'Minimum length-5 characters'
  %p
    = f.submit 'Add'

app/views/hotels/edit.html.haml
%br
%h1 Edit hotel
%br
= simple_form_for :hotel, :url => hotel_path(@hotel), :method => :put do |f|
  - if @hotel.errors.any?
    #error_explanation
    %h2
      = pluralize(@hotel.errors.count, "error")
      prohibited this article from being saved:
    %ul
      - @hotel.errors.full_messages.each do |msg|
        %li= msg
  %table{:border => "0", :cellpadding => "5px"}
    %tr
      %td
        %p
          = f.label :title
      %td
        = f.text_field :title
    %tr
      %td
        = f.label :breakfast, required: false
      %td
        = f.input_field :breakfast, as: :boolean, boolean_style: :inline
    %tr
      %td
        = f.label :description, required: false
      %td
        = f.text_area :description
    %tr
      %td
        = f.label :photo, required: false
      %td
        = f.input :photo, as: :file, required: false, label:false
    %tr
      %td
        = f.label :price, required: false
      %td
        = f.text_field :price
    %tr
      %td
        = f.label :country, required: false
      %td
        = f.text_field :country
    %tr
      %td
        = f.label :state, required: false
      %td
        = f.text_field :state
    %tr
      %td
        = f.label :city, required: false
      %td
        = f.text_field :city
    %tr
      %td
        = f.label :street, required: false
      %td
        = f.text_field :street
    %tr
      %td
        =link_to 'Get back', hotels_path, {class: 'button-back'}
      %td
        = f.button :submit

app/views/hotels/index.html.haml
= link_to new_hotel_path, {class:'button bb'} do
  %span
    Add hotel
%div.list
  %h1 Hotels
  %br
  - @hotels.each do |hotel|
    %div.hotel
      - if hotel.photo.file.nil?
        %img{:alt => "hotel photo", :src => "/img/no-hotel.png", :width => "200"}
      - else
        %img{:alt => "hotel photo", :src => hotel.photo.thumb, :width => "200"}
      %div.data
        - if hotel.title.length > 12
          %h2
            %marquee
              =hotel.title
        -else
          %h2
            =hotel.title
        %p=rating_for hotel, 'rating', disable_after_rate: true
        %p
          Breakfast included: #{ hotel.breakfast==1 ? " Yes" :" No" }
        - if !hotel.price.nil?
          %p
            Price for room:#{hotel.price} $
        -else
          %p &nbsp;
        = link_to hotel_path(hotel), {class: 'button'} do
          %span
            Read More
%br
= paginate @hotels

app/views/hotels/new.html.haml
%h1 New hotel
= simple_form_for :hotel, :url => hotels_path, :method => :post do |f|
  - if @hotel.errors.any?
    #error_explanation
    /%h2
    /  = pluralize(@hotel.errors.count, "error")
    /  prohibited this article from being saved:
    %ul
      - @hotel.errors.full_messages.each do |msg|
        %li
          ERROR:
          = msg
  %table{:border => "0", :cellpadding => "5px"}
    %tr
      %td
        %p
          = f.label :title
      %td
        = f.text_field :title
    %tr
      %td
        = f.label :breakfast, required: false
      %td
        = f.input_field :breakfast, as: :boolean, boolean_style: :inline
    %tr
      %td
        = f.label :description, required: false
      %td
        = f.text_area :description
    %tr
      %td
        = f.label :photo, required: false
      %td
        = f.input :photo, as: :file, required: false, label:false
    %tr
      %td
        = f.label :price, required: false
      %td
        = f.input :price, as: :integer, required: false, label:false
    %tr
      %td
        = f.label :country, required: false
      %td
        = f.text_field :country
    %tr
      %td
        = f.label :state, required: false
      %td
        = f.text_field :state
    %tr
      %td
        = f.label :city, required: false
      %td
        = f.text_field :city
    %tr
      %td
        = f.label :street, required: false
      %td
        = f.text_field :street
    %tr
      %td
        =f.button :button do
          =link_to 'Get back', hotels_path, {class: 'button-back'}
      %td
        = f.button :submit

app/views/hotels/show.html.haml
%br
%h1
  =@hotel.title
%br
  %div.hotel-full
    - if @hotel.photo.file.nil?
      %img{:alt => "hotel photo", :src => "/img/no-hotel-400.png", :width => "400"}
    - else
      %img{:alt => "hotel photo", :src => @hotel.photo.url, :width => "400"}
    %div.data
      %p= rating_for @hotel, 'rating', disable_after_rate: false, cancel: true
      %p
        Breakfast included: #{ @hotel.breakfast==1 ? " Yes" :" No" }
      - if !@hotel.price.nil?
        %p
          Price for room: #{@hotel.price}$
      - if !@hotel.description.eql?("")
        %p
          Room description:
          = @hotel.description
      - if !(@hotel.country && @hotel.state && @hotel.city && @hotel.street)
        %p
          Address:
          = @hotel.country + ", " + @hotel.state + ", "  + @hotel.city + ", "  + @hotel.street

      - if @hotel.user == current_user
        = link_to edit_hotel_path(@hotel), {class: 'button'} do
          %span
            Edit hotel
        = link_to hotel_path, method: :delete, data: { confirm: 'Do you want to delete hotel?' }, class: 'button' do
          %span
            Delete hotel
%div.comments
  %hr 
  %br
  %h2 Comments
  %br
  
  -if @hotel.comments.length > 0
    = render @hotel.comments
  -else
    %p No comments
  - if user_signed_in?
    
    %br
    %h2 Add a comment:
    %br
    %div.mail-pass
      =render 'comments/comment_form'
  - else
    %strong #{ link_to 'Sign in', new_user_session_path} or #{ link_to 'sign up', new_user_registration_path} to leave the comment

app/views/layouts/_footer.html.haml
%footer
  .container
    %p &copy; JetRuby Labs

app/views/layouts/_header.html.haml
%header
  .container
    .logo-box
      %h1.logo
        %a{:href => root_path}
          HotelGuide
    %nav
      %ul.menu
        %li
          = link_to "Help", help_path
        %li
          - if user_signed_in?
            = link_to "Sign out", destroy_user_session_path, method: :delete
          - else
            = link_to "Sign in", new_user_session_path
        %li
          = link_to "Contact", contact_path
        %li
          = link_to "About",   about_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container.body
      %ul.breadcrumb
        = render_breadcrumbs :tag => :li, :separator => ''
      = yield
    .clear
    = render 'layouts/footer'
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%h1 About Us
%p
  The
  %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development
  with
  = succeed "." do
    %a{:href => "http://rubyonrails.org/"} Ruby on Rails
  This
  is the sample application for the tutorial.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  = succeed "." do
    %a{:href => "http://railstutorial.org/contact"} contact page

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  = succeed "." do
    %a{:href => "http://railstutorial.org/help"} Rails Tutorial help page
  To get help on this sample app, see the
  = succeed "." do
    %a{:href => "http://railstutorial.org/book"} Rails Tutorial book